// Master list of source sites Capital Watch crawls for funding opportunities. The
// pipeline rotates through this in batches (see ROTATION_BATCH_SIZE in
// capitalWatchPipeline.cjs) instead of re-crawling all of them every run, so each
// weekly run covers fresh ground rather than re-hitting the same heavily-linked
// sites (which is what was eating the page budget on masschallenge.org/clear.co).
module.exports = [
  'https://www.challenge.gov',
  'https://www.opengrants.io',
  'https://www.dodsbirsttr.mil',
  'https://www.xtechsearch.army.mil',
  'https://seedfund.nsf.gov',
  'https://www.mbda.gov',
  'https://www.angel.co',
  'https://www.angelcapitalassociation.org',
  'https://www.gust.com',
  'https://www.hiversandstrivers.com',
  'https://www.blackangelsmiami.com',
  'https://www.keiretsuforum.com',
  'https://www.gitcoin.co',
  'https://esp.ethereum.foundation',
  'https://solana.org/grants',
  'https://grants.web3.foundation',
  'https://devpost.com/hackathons',
  'https://dorahacks.io',
  'https://ethglobal.com',
  'https://celopg.eco',
  'https://prezenti.xyz',
  'https://lisk.com/grants',
  'https://www.veteranventures.us',
  'https://www.collab.capital',
  'https://www.harlem.capital',
  'https://www.backstagecapital.com',
  'https://startup.google.com/founders-fund',
  'https://www.blackambitionprize.com',
  'https://masschallenge.org',
  'https://startupworldcup.io',
  'https://www.sxsw.com/pitch',
  'https://extremetechchallenge.org',
  'https://hello-tomorrow.org',
  'https://veteransbusinessbattle.org',
  'https://secondservicefoundation.org',
  'https://www.warriorrising.org',
  'https://www.revolution.com/rise-of-the-rest',
  'https://www.investatlanta.com',
  'https://www.veteranloanfund.com',
  'https://aofund.org',
  'https://www.lendistry.com',
  'https://bcfcapital.com',
  'https://www.clear.co',
  'https://www.kiva.org/business',
  'https://www.sba.gov/business-guide/grow-your-business/veteran-owned-businesses',
  'https://streetshares.com',
  'https://www.naacp.org',
];
