'use strict'

const FROM_EMAIL = { name: 'Capital Watch', email: process.env.EMAIL_FROM || 'support@wanderwork.io' }

function escapeHtml(str) {
  return String(str || '').replace(/[&<>"']/g, (c) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[c]))
}

function weeklyDigestEmail(newGrants, dashboardUrl) {
  const rows = newGrants.map(g => `
    <li style="margin-bottom:14px;">
      <a href="${g.link}" style="color:#306770;font-weight:700;text-decoration:none;">${escapeHtml(g.title)}</a>
      <div style="font-size:13px;color:#6b7280;">${escapeHtml(g.agency || '')} &middot; ${escapeHtml(g.fundingType || '')} &middot; ${g.amountUsd ? '$' + g.amountUsd : 'Amount not stated'}</div>
    </li>`).join('')

  const html = `
    <div style="font-family:Arial,sans-serif;color:#333;max-width:600px;margin:0 auto;">
      <h1 style="color:#1f2937;">Capital Watch — ${newGrants.length} new funding opportunit${newGrants.length === 1 ? 'y' : 'ies'}</h1>
      <ul style="padding-left:18px;">${rows}</ul>
      <p style="margin-top:24px;"><a href="${dashboardUrl}" style="background:#FACC15;color:#000;padding:10px 20px;border-radius:6px;text-decoration:none;font-weight:700;">Review on the dashboard →</a></p>
    </div>`

  return {
    from: FROM_EMAIL,
    subject: `Capital Watch: ${newGrants.length} new funding opportunit${newGrants.length === 1 ? 'y' : 'ies'} found`,
    html,
  }
}

function applicationDraftEmail(grant, companyName) {
  const html = `
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    h2 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; margin-top: 30px; }
    .section { margin-bottom: 30px; }
    .detail-row { margin: 8px 0; }
    .label { font-weight: bold; color: #555; }
    .content { background-color: #f9f9f9; padding: 15px; border-left: 4px solid #3498db; margin: 15px 0; white-space: pre-wrap; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #777; font-size: 12px; }
  </style>
</head>
<body>
  <h1>📄 Application Draft Ready — ${escapeHtml(companyName)}</h1>

  <div class="section">
    <h2>Opportunity Details</h2>
    <div class="detail-row"><span class="label">Title:</span> ${escapeHtml(grant.title || 'Untitled')}</div>
    <div class="detail-row"><span class="label">Agency:</span> ${escapeHtml(grant.agency || 'Unknown')}</div>
    <div class="detail-row"><span class="label">Type:</span> ${escapeHtml(grant.fundingType || 'grant')}</div>
    <div class="detail-row"><span class="label">Amount:</span> ${grant.amountUsd ? '$' + grant.amountUsd : 'N/A'}</div>
    <div class="detail-row"><span class="label">Deadline:</span> ${grant.rolling ? 'Rolling' : (grant.dueDate || 'N/A')}</div>
    <div class="detail-row"><span class="label">Link:</span> <a href="${grant.link}">${escapeHtml(grant.link || 'N/A')}</a></div>
    <div class="detail-row"><span class="label">Requirements:</span> ${escapeHtml(grant.requirements || 'Not stated')}</div>
  </div>

  <div class="section">
    <h2>Outreach Email</h2>
    <div class="content">${escapeHtml(grant.outreachEmail || 'N/A')}</div>
  </div>

  <div class="section">
    <h2>Application Narrative</h2>
    <div class="content">${escapeHtml(grant.applicationNarrative || 'N/A')}</div>
  </div>

  <div class="footer">
    <p><strong>Next Steps:</strong></p>
    <ul>
      <li>Review and edit the draft as needed</li>
      <li>Confirm it follows the stated requirements above</li>
      <li>Copy/paste into the application portal and submit before the deadline</li>
    </ul>
    <p style="margin-top: 20px;">Generated by Capital Watch for ${escapeHtml(companyName)}</p>
  </div>
</body>
</html>`

  return {
    from: FROM_EMAIL,
    subject: `Application Draft (${companyName}): ${grant.agency || grant.title}`,
    html,
  }
}

module.exports = { weeklyDigestEmail, applicationDraftEmail }
